/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminAuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorEmail', 'actorId', 'createdAt', 'id', 'summary', 'targetEmail', 'targetUserId'] as const
  $columns = AdminAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorEmail: string | null
  @column()
  declare actorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare summary: string
  @column()
  declare targetEmail: string | null
  @column()
  declare targetUserId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoardSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'id', 'imageUrl', 'references', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = BoardSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare references: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class CardAttachmentSchema extends BaseModel {
  static $columns = ['cardId', 'createdAt', 'createdBy', 'fileName', 'fileUrl', 'id', 'mimeType', 'position', 'sizeBytes'] as const
  $columns = CardAttachmentSchema.$columns
  @column()
  declare cardId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column()
  declare fileName: string
  @column()
  declare fileUrl: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string | null
  @column()
  declare position: number | null
  @column()
  declare sizeBytes: number | null
}

export class CardSchema extends BaseModel {
  static $columns = ['columnId', 'createdAt', 'createdBy', 'description', 'groupId', 'id', 'imageUrl', 'isArchived', 'isDeleted', 'linkTitle', 'linkUrl', 'position', 'title', 'updatedAt', 'updatedBy', 'version', 'youtubeUrl'] as const
  $columns = CardSchema.$columns
  @column()
  declare columnId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column()
  declare description: string | null
  @column()
  declare groupId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare isArchived: boolean | null
  @column()
  declare isDeleted: boolean | null
  @column()
  declare linkTitle: string | null
  @column()
  declare linkUrl: string | null
  @column()
  declare position: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
  @column()
  declare version: number | null
  @column()
  declare youtubeUrl: string | null
}

export class ColumnSchema extends BaseModel {
  static $columns = ['boardId', 'createdAt', 'createdBy', 'id', 'position', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = ColumnSchema.$columns
  @column()
  declare boardId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class GroupSchema extends BaseModel {
  static $columns = ['columnId', 'createdAt', 'createdBy', 'id', 'position', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = GroupSchema.$columns
  @column()
  declare columnId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class InvitationSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'email', 'id', 'key', 'usedAt', 'usedBy'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare usedBy: number | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['codeHash', 'createdAt', 'email', 'expiresAt', 'id', 'usedAt'] as const
  $columns = PasswordResetSchema.$columns
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class UserBookmarkSchema extends BaseModel {
  static $columns = ['cardId', 'createdAt', 'id', 'userId'] as const
  $columns = UserBookmarkSchema.$columns
  @column()
  declare cardId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isAdmin', 'isMasterAdmin', 'password', 'sessionsValidFrom', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean
  @column()
  declare isMasterAdmin: boolean
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare sessionsValidFrom: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}
